<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateReminderRequest;
use App\Http\Requests\UpdateReminderRequest;
use App\Http\Controllers\AppBaseController;
use App\Models\Reminder;
use App\Models\User;
use App\Repositories\ReminderRepository;
use Illuminate\Http\Request;
use Flash;

class ReminderController extends AppBaseController
{
    /** @var ReminderRepository $reminderRepository*/
    private $reminderRepository;

    public function __construct(ReminderRepository $reminderRepo)
    {
        $this->reminderRepository = $reminderRepo;
    }

    /**
     * Display a listing of the Reminder.
     */
    public function index(Request $request)
    {
        /*
        //code generated by adminLTEGenerated
        $reminders = $this->reminderRepository->paginate(10);

        return view('reminders.index')
            ->with('reminders', $reminders);*/

        $reminders = Reminder::paginate(10);
        return view('reminders.index', compact('reminders'));
    }

    /**
     * Show the form for creating a new Reminder.
     */
    public function create()
    {
        $users = User::pluck('name', 'id');
        return view('reminders.create', compact('users'));
    }

    /**
     * Store a newly created Reminder in storage.
     */
    public function store(CreateReminderRequest $request)
    {
        $input = $request->all();

        $reminder = $this->reminderRepository->create($input);

        Flash::success('Recordatorio guardado correctamente.');

        return redirect(route('reminders.index'));
    }

    /**
     * Display the specified Reminder.
     */
    public function show($id)
    {
        $reminder = $this->reminderRepository->find($id);

        if (empty($reminder)) {
            Flash::error('Reminder not found');

            return redirect(route('reminders.index'));
        }

        return view('reminders.show')->with('reminder', $reminder);
    }

    /**
     * Show the form for editing the specified Reminder.
     */
    public function edit($id)
    {
        $reminder = $this->reminderRepository->find($id);

        if (empty($reminder)) {
            Flash::error('Reminder not found');

            return redirect(route('reminders.index'));
        }
        $users = User::pluck('name', 'id');

        return view('reminders.edit', compact('reminder', 'users'));
    }

    /**
     * Update the specified Reminder in storage.
     */
    public function update($id, UpdateReminderRequest $request)
    {
        $reminder = $this->reminderRepository->find($id);

        if (empty($reminder)) {
            Flash::error('Reminder not found');

            return redirect(route('reminders.index'));
        }

        $reminder = $this->reminderRepository->update($request->all(), $id);

        Flash::success('Recordatorio actualizado correctamente.');

        return redirect(route('reminders.index'));
    }

    /**
     * Remove the specified Reminder from storage.
     *
     * @throws \Exception
     */
    public function destroy($id)
    {
        $reminder = $this->reminderRepository->find($id);

        if (empty($reminder)) {
            Flash::error('Reminder not found');

            return redirect(route('reminders.index'));
        }

        $this->reminderRepository->delete($id);

        Flash::success('Reminder deleted successfully.');

        return redirect(route('reminders.index'));
    }
}
